import { createSlice } from "@reduxjs/toolkit"; 

// Creating a slice for managing favorites
const favoritesSlice = createSlice({
    // The name of the slice, which will be used as a prefix for generated action types
    name: "favorites",
    
    // The initial state for the reducer
    initialState: [],
    
    // An object of "case reducers" where the key names will become the action type strings
    reducers: {
        // Action to add a favorite
        addFavorite(state, action) {
            // Check if the item is already in the favorites list based on its trackId
            if (!state.some(item => item.trackId === action.payload.trackId)) {
                // If not in favorites, push the item to the state
                state.push(action.payload);
            }
        },
        // Action to remove a favorite
        removeFavorite(state, action) {
            console.log("Current state:", state);  // Logging the current state for debugging purposes
            console.log("Action payload:", action.payload);  // Logging the action payload for debugging purposes
            
            // Filter out the item from the state based on its trackId and return the new state
            return state.filter(item => item.trackId !== action.payload.trackId);
        }
    }
});

// Exporting the action creators generated by createSlice
export const { addFavorite, removeFavorite } = favoritesSlice.actions;

// Exporting the reducer function that handles the actions
export default favoritesSlice.reducer;

