import { createSlice } from '@reduxjs/toolkit';

// Slice to manage the UI state, such as loading and error states
const uiSlice = createSlice({
    name: 'ui',  // Name of the slice, used to prefix the generated action types
    
    // Initial state values for this slice
    initialState: {
        loading: false,  // Indicates if a loading operation is in progress
        error: null,     // Stores error message, if any
    },
    
    reducers: {
        // Action to set the loading state
        setLoading: (state, action) => {
            state.loading = action.payload;  // Update the loading state with the payload value (true or false)
        },
        
        // Action to set an error message
        setError: (state, action) => {
            state.error = action.payload;  // Set the error state with the provided error message
        },
        
        // Action to clear any existing error message
        clearError: (state) => {
            state.error = null;  // Reset the error state to null
        }
    },
});

// Exporting the actions generated by the slice for use in components or other slices
export const { setLoading, setError, clearError } = uiSlice.actions;

// Exporting the reducer function to handle state updates based on dispatched actions
export default uiSlice.reducer;

